python: 2.7

install:
  - pip install -i http://pypi.douban.com/simple -r requirements.txt

before_script:
  - python -m ctsrunner.download
  - python -m ctsrunner.prepare

script:
  - python -m ctsrunner.run

after_script:
  - echo "after_script"