python: 2.7

install:
  - echo "Install..."
  - pip install -i http://pypi.douban.com/simple -r requirements.txt

before_script:
  - echo "Before script..."

script:
  - python startCTS.py

after_script:
  - echo "after_script"